export const AUDIT_ENTITY_TYPES = [
  "analytics_settings",
  "announcement",
  "audit_archive_export",
  "audit_log_export",
  "badge",
  "event",
  "event_participant",
  "event_poll_vote",
  "gallery",
  "game_data",
  "gallery_item",
  "guild_war",
  "guild_war_history",
  "guild_war_member_stats",
  "invite_link",
  "media_cleanup",
  "member_badge",
  "member_profile",
  "recurring_template",
  "role",
  "seed",
  "user",
  "user_auth",
  "wiki",
  "wiki_article",
  "wiki_category",
] as const;

export type AuditEntityType = (typeof AUDIT_ENTITY_TYPES)[number];

export const AUDIT_ACTIONS = [
  "admin_create_member",
  "archive",
  "assign",
  "batch_add_by_moderator",
  "batch_deactivate",
  "batch_delete",
  "batch_reactivate",
  "batch_remove_by_moderator",
  "batch_role_update",
  "batch_update",
  "change_password",
  "change_username",
  "complete",
  "conclude",
  "create",
  "create_video",
  "deactivate",
  "delete",
  "delete_audio",
  "delete_avatar",
  "delete_images",
  "download_raw_ndjson_gz",
  "export_filtered_csv",
  "export_filtered_json",
  "init",
  "join",
  "leave",
  "move_member",
  "pause",
  "raffle_draw",
  "reactivate",
  "register",
  "reset_password",
  "rollback",
  "run",
  "resume",
  "revoke",
  "save_teams",
  "set_role_tag",
  "unassign",
  "update",
  "update_role",
  "upload",
  "upload_audio",
  "upload_avatar",
  "upload_icon",
  "upload_images",
  "vote",
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number];
